appname: "Fever_backend"
mode: "dev"
port: 8080

mysql:
  host: 47.98.212.252
  port: 3306
  user: root
  password: 123456
  db: fever
  max_open_conns: 1000
  max_idle_conns: 20

log:
  level: "debug"
  filename: "./log/blog.log"
  max_size: 10000
  max_age: 3600
  max_backups: 5